version: '3.4'
services:
  mykitchen.microservices.identity.api.rest:
    container_name: mykitchen.microservices.identity.api.rest
    image: sirmov/mykitchen-identity-service
    build:
      context: ../../../
      dockerfile: src/Microservices/Identity/Dockerfile
    depends_on:
      mykitchen.microservices.identity.mongodb:
        condition: service_started
      mykitchen.microservices.identity.redis:
        condition: service_started
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file: "secrets/identity.env"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001

  mykitchen.microservices.identity.mongodb:
    container_name: mykitchen.microservices.identity.mongodb
    image: mongo
    restart: always
    env_file: "secrets/mongo.env"
    ports:
      - "27017:27017"
    volumes:
      - mykitchen-identity-mongodb:/data/db

  mykitchen.microservices.identity.redis:
    container_name: mykitchen.microservices.identity.redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - mykitchen-identity-redis:/data

volumes:
  mykitchen-identity-mongodb: 
  mykitchen-identity-redis:
  
