FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83 AS build

# Restoring
WORKDIR /App
COPY Microservices/Identity ./Microservices/Identity
COPY Common ./Common
WORKDIR /App/Microservices/Identity/Api/MyKitchen.Microservices.Identity.Api.Grpc
ARG BUILD_CONFIGURATION=Release
RUN dotnet restore "MyKitchen.Microservices.Identity.Api.Grpc.csproj"

# Building
WORKDIR /App/Microservices/Identity/Api/MyKitchen.Microservices.Identity.Api.Grpc
RUN dotnet build "MyKitchen.Microservices.Identity.Api.Grpc.csproj" -c ${BUILD_CONFIGURATION} --no-restore

# Publishing
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR /App/Microservices/Identity/Api/MyKitchen.Microservices.Identity.Api.Grpc
RUN dotnet publish "MyKitchen.Microservices.Identity.Api.Grpc.csproj" -c ${BUILD_CONFIGURATION} --no-build -o /App/publish /p:UseAppHost=false

# Running
FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:6c4df091e4e531bb93bdbfe7e7f0998e7ced344f54426b7e874116a3dc3233ff AS runtime
WORKDIR /App
COPY --from=publish /App/publish .
EXPOSE 5100
EXPOSE 5101
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5100

ENTRYPOINT ["dotnet", "MyKitchen.Microservices.Identity.Api.Grpc.dll"]
