apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykitchen-microservices-identity-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mykitchen-microservices-identity-mongo
  template:
    metadata:
      labels:
        app: mykitchen-microservices-identity-mongo
    spec:
      containers:
        - name: mykitchen-microservices-identity-redis
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
