blank_issues_enabled: false
contact_links:
  - name: "Feature Request"
    url: "/issues/new?template=feature-request.md"
    about: "Request a new feature or improvement."
  - name: "Bug Report"
    url: "/issues/new?template=bug-report.md"
    about: "Report a bug or unexpected behavior in the project."
  - name: "Task"
    url: "/issues/new?template=task.md"
    about: "Create a task for ongoing work."
  - name: "User Story"
    url: "/issues/new?template=user-story.md"
    about: "Create a user story to describe a feature."
  - name: "Epic"
    url: "/issues/new?template=epic.md"
    about: "Create a epic to describe a larger body of work consisting of multiple features."
  - name: "Refactoring"
    url: "/issues/new?template=refactoring.md"
    about: "Create a task related to improving code quality, performance, or refactoring existing work."
  - name: "Chore"
    url: "/issues/new?template=chore.md"
    about: "Create a maintenance or non-functional tasks linked with the project."
  - name: "Spike"
    url: "/issues/new?template=spike.md"
    about: "Create a research task to resolve technical or design uncertainty."
