FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83 AS build

# Restoring
WORKDIR /App
COPY Microservices/Recipes ./Microservices/Recipes
COPY Common ./Common
WORKDIR /App/Microservices/Recipes/Api/MyKitchen.Microservices.Recipes.Api.Rest
ARG BUILD_CONFIGURATION=Release
RUN dotnet restore "MyKitchen.Microservices.Recipes.Api.Rest.csproj"

# Building
WORKDIR /App/Microservices/Recipes/Api/MyKitchen.Microservices.Recipes.Api.Rest
RUN dotnet build "MyKitchen.Microservices.Recipes.Api.Rest.csproj" -c ${BUILD_CONFIGURATION} --no-restore

# Publishing
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR /App/Microservices/Recipes/Api/MyKitchen.Microservices.Recipes.Api.Rest
RUN dotnet publish "MyKitchen.Microservices.Recipes.Api.Rest.csproj" -c ${BUILD_CONFIGURATION} --no-build -o /App/publish /p:UseAppHost=false

# Running
FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:6c4df091e4e531bb93bdbfe7e7f0998e7ced344f54426b7e874116a3dc3233ff AS runtime
WORKDIR /App
COPY --from=publish /App/publish .
EXPOSE 6000
EXPOSE 6001
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:6000

ENTRYPOINT ["dotnet", "MyKitchen.Microservices.Recipes.Api.Rest.dll"]
